name: CI Pipeline
on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    services:
      mongo:
        image: mongo:5.0
        ports:
          - 27017:27017
        options: >-
          --health-cmd "mongo --eval 'db.runCommand({ ping: 1 })'"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-cov httpx python-dotenv
          
      - name: Patch MQTT Client for Tests
        run: |
          # Find the line where mqtt_client.start() is called and comment it out
          sed -i 's/mqtt_client.start()/# mqtt_client.start() # Disabled for tests/g' core/mqtt_client.py
          # Verify the change
          grep -A 1 -B 1 "mqtt_client.start" core/mqtt_client.py || echo "MQTT client start call successfully patched"

      - name: Run Tests
        env:
          MONGO_URL: mongodb://localhost:27017
          PYTHONPATH: ${{ github.workspace }}
          MQTT_ENABLED: "false"
          TEST_MODE: "true"
        run: pytest --cov=.

  lint:
    name: Lint Code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Linter
        run: pip install flake8

      - name: Run Linter
        run: |
          flake8 . \
            --max-line-length=120 \
            --ignore=E501,F401,W291,W292,W293,E401 \
            --exclude=.git,__pycache__,env,venv,.venv
