name: CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H 20.77.112.61 >> ~/.ssh/known_hosts

    - name: SSH into VM and Deploy
      run: |
        ssh -o StrictHostKeyChecking=no azureuser@20.77.112.61 << 'EOF'
          cd /home/azureuser/Backend
          
          git pull origin main
          
          source venv/bin/activate
          
          pip install -r requirements.txt
          
          pkill -f 'uvicorn'

          nohup uvicorn main:app --host 0.0.0.0 --port 8000 --reload &
        EOF

    - name: Send deployment notification
      run: |
        echo "Deployment Successful!"
